services:
  app:
    build:
      context: .
      target: dev
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./app
          target: /app/app
          action: sync
        - path: ./components
          target: /app/components
          action: sync
        - path: ./lib
          target: /app/lib
          action: sync
        - path: ./data.json
          target: /app/data.json
          action: sync
        - path: ./public
          target: /app/public
          action: sync
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/node_modules

volumes:
  node_modules:
